FROM golang:alpine as build

WORKDIR /app

COPY . .

RUN go mod download

RUN GOOS=linux go build -ldflags="-w -s" -o assignment

# FROM gcr.io/distroless/base-debian12

# WORKDIR /

# COPY --from=build /app/assignment .

CMD [ "./assignment" ]
