package models

// Generated by https://quicktype.io

type Challenge struct {
	CorID             string   `json:"corId" bson:"corId"`
	ChallengeName     string   `json:"challengeName" bson:"challengeName"`
	CreatorName       string   `json:"creatorName" bson:"creatorName"`
	ImageName         string   `json:"imageName" bson:"imageName"`
	ImageTag          string   `json:"imageTag" bson:"imageTag"`
	ImageRegistryLink string   `json:"imageRegistryLink" bson:"imageRegistryLink"`
	Duration          int64    `json:"duration" bson:"duration"`
	Participants      []string `json:"participants" bson:"participants"`
}
